### ISSUE TITLE
Please don't hesitate to ask for help!

### ISSUE THREAD

**Issue by Naereen** [pcotret/gnuradio-tutorial#1]
Great initiative :clap: !

**Comment by pcotret** [comment]
I'll start to update it this weekend.
I have a doubt for the repository structure: if I continue, the README file will be (very) very long...

Another structure could be:
- Brief README + solutions (GNURadio modules ready-to-use)
- A wiki with full instructions for my exercises (maybe easier to create links, subsections, etc)

**Comment by Naereen** [comment]
I am in favor of a wiki, you can add collaborators easily.

The C++/Python solutions can be in one directory for each exercise.

**Comment by pcotret** [comment]
Something like the new repository I'm writing ;)
https://github.com/pcotret/gr-tutorial
